language: node_js
node_js: stable


cache:
  directories:
    - node_modules

before_deploy:
  - "npm run build"
  - "ls -l dist"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  file_glob: true
  on:
    branch: master
